#!/bin/bash

function main
{
    #
    # verify pre-conditions, fail early, these coditions will be alos checked again on the remote host
    #

    [ "${id}" = "" ] && { echo "[error]: the id not specified" 1>&2; exit 1; }

    [ "${private_ip}" = "" ] && { echo "[error]: the private IP not specified, use --private-ip" 1>&2; exit 1; }

    [ "${java_archive_file}" = "" ] && { echo "[error]: java archive file not specified. Use --java to indicate a java archive file in the archive directory ${archive_dir}" 1>&2; exit 1; }
    [ -f ${archive_dir}/${java_archive_file} ] || { echo "[error]: java archive file ${archive_dir}/${java_archive_file} does not exist" 1>&2; exit 1; }

    [ "${amq_archive_file}" != "" -a ! -f ${archive_dir}/${amq_archive_file} ] && { echo "[error]: A-MQ archive file ${archive_dir}/${amq_archive_file} does not exist" 1>&2; exit 1; }

    [ "${jboss_archive_file}" != "" -a ! -f ${archive_dir}/${jboss_archive_file} ] && { echo "[error]: JBoss archive file ${archive_dir}/${jboss_archive_file} does not exist" 1>&2; exit 1; }

    # we will need to update the local /etc/hosts as part of this procedure,
    # verify that we have sufficient permissions

}

main $@
