#!/bin/bash

function main
{
    while [ "$1" != "" ]; do
        if [ "$1" = "--java" ]; then
            shift
            java_archive_file=$1
        elif [ "$1" = "--amq" ]; then
            shift
            amq_archive_file=$1
        elif [ "$1" = "--jboss" ]; then
            shift
            jboss_archive_file=$1
        fi
        shift
    done

    local users="root ec2-user"

    for user in ${users}; do
        setup-environment-private-key ${user} ${environment_private_key_file}
        setup-environment-public-key ${user} ${environment_private_key_file}
    done

    link-to-ec2-host ${id} /nfs/bin

    if [ "${jboss_archive_file}" != "" ]; then
        # load the jboss library
        [ -f $(dirname $0)/jboss.shlib ] && . $(dirname $0)/jboss.shlib || \
            { echo "we need to install JBoss but we did not find the JBoss library $(dirname $0)/jboss.shlib " 1>&2; exit 1; }

        install-jboss ${id} ${jboss_archive_file}
    fi
}
