#!/bin/bash

function main
{
    while [ "$1" != "" ]; do
        if [ "$1" = "--java" ]; then
            shift
            java_archive_file=$1
        elif [ "$1" = "--amq" ]; then
            shift
            amq_archive_file=$1
        elif [ "$1" = "--eap" ]; then
            shift
            eap_archive_file=$1
        fi
        shift
    done

    local users="root ec2-user"

    for user in ${users}; do
        setup-environment-private-key ${user} ${environment_private_key_file}
        setup-environment-public-key ${user} ${environment_private_key_file}
    done

    link-to-ec2-host ${id} /nfs/bin

    install_java ${java_archive_file} /nfs/archive

    for user in ${users}; do
        update-bashrc-with-java-information ${user} /opt/java
    done

    if [ "${amq_archive_file}" != "" ]; then
        # load the amq library
        [ -f $(dirname $0)/amq.shlib ] && . $(dirname $0)/amq.shlib || \
            { echo "we need to install A-MQ but we did not find the A-MQ library $(dirname $0)/amq.shlib " 1>&2; exit 1; }

        install-amq ${id} ${amq_archive_file}
    fi

    if [ "${eap_archive_file}" != "" ]; then
        # load the eap library
        [ -f $(dirname $0)/eap.shlib ] && . $(dirname $0)/eap.shlib || \
            { echo "we need to install EAP but we did not find the EAP library $(dirname $0)/eap.shlib " 1>&2; exit 1; }

        install-eap ${id} ${eap_archive_file}
    fi
}
