#!/bin/bash

function main()
{
    local short_class_name
    local debug=false
    local arguments

    while [ "$1" != "" ]; do
        if [ "$1" = "--debug" ]; then
            debug=true
            debug_arg="--debug"
        elif [ "${short_class_name}" = "" ]; then
            short_class_name=$1
        else
            [ "${arguments}" = "" ] && arguments="$1" || arguments="${arguments} $1"
        fi
        shift
    done

classpath="\
$(dirname $0)/../../../../target/em-1.0-SNAPSHOT.jar:\
$(dirname $0):\
${M2}/log4j/log4j/1.2.17/log4j-1.2.17.jar"

    command="java -cp ${classpath} com.novaordis.em.parser.${short_class_name} ${arguments}"

    ${debug} && echo "${command}"
    ${command}
}

main $@